//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticCompanyLO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Code_Driver { get; set; }
        public string Surname_Driver { get; set; }
        public string Name_Driver { get; set; }
        public string Midname_Driver { get; set; }
        public Nullable<int> Code_Personal_Data { get; set; }
        public Nullable<int> Code_Executor { get; set; }
        public string Boundaries_Work { get; set; }
    
        public virtual Personal_Data Personal_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Executors Executors { get; set; }
    }
}
