//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticCompanyLO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Code_Order { get; set; }
        public Nullable<System.DateTime> Date_Order { get; set; }
        public Nullable<int> Code_Executor { get; set; }
        public Nullable<int> Code_Driver { get; set; }
        public Nullable<int> Code_Vehicle { get; set; }
        public Nullable<System.DateTime> Date_Loading { get; set; }
        public string Address_Loading { get; set; }
        public string Shipper_Name { get; set; }
        public string Shipper_Telephone { get; set; }
        public string Cargo_Name { get; set; }
        public string Conditions_Transportation { get; set; }
        public Nullable<System.DateTime> Date_Unloading { get; set; }
        public string Address_Unloading { get; set; }
        public string Consignee_Name { get; set; }
        public string Consignee_Telephone { get; set; }
        public string Route_Name { get; set; }
        public string Transportation_Format { get; set; }
        public string Cost_Payment { get; set; }
        public Nullable<bool> Status_Order { get; set; }
        public Nullable<bool> Executor_Is_Driver { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Executors Executors { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
