//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticCompanyLO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Data()
        {
            this.Drivers = new HashSet<Drivers>();
            this.Executors = new HashSet<Executors>();
        }
    
        public int Code_Personal_Data { get; set; }
        public string Passport_Numbers { get; set; }
        public string Passport_Division_Code { get; set; }
        public Nullable<System.DateTime> Passport_Date_Issued { get; set; }
        public string Passport_Issued { get; set; }
        public string Telephone_Number { get; set; }
        public Nullable<int> Id_Ati { get; set; }
        public string Driver_License_Numbers { get; set; }
        public Nullable<System.DateTime> Driver_License_Date_Issued { get; set; }
        public string Tin_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivers> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Executors> Executors { get; set; }
    }
}
