//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticCompanyLO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int Code_Vehicle { get; set; }
        public Nullable<int> Code_Executor { get; set; }
        public Nullable<int> Code_Category { get; set; }
        public string Brand_Vehicle { get; set; }
        public string Model_Vehicle { get; set; }
        public Nullable<float> Length_Vehicle { get; set; }
        public Nullable<float> Width_Vehicle { get; set; }
        public Nullable<float> Height_Vehicle { get; set; }
        public Nullable<float> Tonnage_Vehicle { get; set; }
        public Nullable<float> Volume_Vehicle { get; set; }
        public string Number_Vehicle { get; set; }
        public Nullable<int> Code_Download_Type { get; set; }
        public Nullable<int> Code_Additionally_Parameter { get; set; }
    
        public virtual Additionally_Parameters Additionally_Parameters { get; set; }
        public virtual Category_Trailer Category_Trailer { get; set; }
        public virtual Download_Types Download_Types { get; set; }
        public virtual Executors Executors { get; set; }
    }
}
